export const userTableData = [
  {
    id: 1,
    name: "Daniel Fatoyinbo",
    email: "daniel.fatoyinbo@example.com",
    phone: "08031234567",
    userType: "Admin",
    status: "Active",
  },
  {
    id: 2,
    name: "Mercy Adewale",
    email: "mercy.adewale@example.com",
    phone: "08123456789",
    userType: "Customer",
    status: "Suspended",
  },
  {
    id: 3,
    name: "John Okoro",
    email: "john.okoro@example.com",
    phone: "07012345678",
    userType: "Vendor",
    status: "Active",
  },
  {
    id: 4,
    name: "Fatima Bello",
    email: "fatima.bello@example.com",
    phone: "09087654321",
    userType: "Customer",
    status: "Suspended",
  },
  {
    id: 5,
    name: "Emeka Uche",
    email: "emeka.uche@example.com",
    phone: "08109876543",
    userType: "Admin",
    status: "Active",
  },
  {
    id: 6,
    name: "Chinelo Okafor",
    email: "chinelo.okafor@example.com",
    phone: "08056789012",
    userType: "Vendor",
    status: "Suspended",
  },
  {
    id: 7,
    name: "Ibrahim Salami",
    email: "ibrahim.salami@example.com",
    phone: "07076543210",
    userType: "Customer",
    status: "Active",
  },
  {
    id: 8,
    name: "Linda Ojo",
    email: "linda.ojo@example.com",
    phone: "09012345670",
    userType: "Customer",
    status: "Active",
  },
  {
    id: 9,
    name: "Tunde Adebayo",
    email: "tunde.adebayo@example.com",
    phone: "08134567890",
    userType: "Admin",
    status: "Suspended",
  },
  {
    id: 10,
    name: "Grace Oyetola",
    email: "grace.oyetola@example.com",
    phone: "08023456789",
    userType: "Vendor",
    status: "Active",
  },
  {
    id: 11,
    name: "Ahmed Musa",
    email: "ahmed.musa@example.com",
    phone: "07099887766",
    userType: "Customer",
    status: "Active",
  },
  {
    id: 12,
    name: "Victoria Ibe",
    email: "victoria.ibe@example.com",
    phone: "08112233445",
    userType: "Vendor",
    status: "Suspended",
  },
  {
    id: 13,
    name: "Bola Obasanjo",
    email: "bola.obasanjo@example.com",
    phone: "08044332211",
    userType: "Admin",
    status: "Active",
  },
  {
    id: 14,
    name: "Paul Ikenna",
    email: "paul.ikenna@example.com",
    phone: "09055667788",
    userType: "Customer",
    status: "Suspended",
  },
  {
    id: 15,
    name: "Aisha Lawal",
    email: "aisha.lawal@example.com",
    phone: "08133445566",
    userType: "Vendor",
    status: "Active",
  },
  {
    id: 16,
    name: "Yusuf Garba",
    email: "yusuf.garba@example.com",
    phone: "07022334455",
    userType: "Customer",
    status: "Suspended",
  },
  {
    id: 17,
    name: "Adaeze Nnamdi",
    email: "adaeze.nnamdi@example.com",
    phone: "08066778899",
    userType: "Admin",
    status: "Active",
  },
  {
    id: 18,
    name: "Samson Eze",
    email: "samson.eze@example.com",
    phone: "09044556677",
    userType: "Vendor",
    status: "Active",
  },
  {
    id: 19,
    name: "Opeyemi Alade",
    email: "opeyemi.alade@example.com",
    phone: "08177889900",
    userType: "Customer",
    status: "Suspended",
  },
  {
    id: 20,
    name: "Chigozie Obi",
    email: "chigozie.obi@example.com",
    phone: "07088990011",
    userType: "Vendor",
    status: "Active",
  },
];
