export const tableData = [
  {
    id: 1,
    companyName: "SwiftLogix",
    ownerName: "Daniel Fatoyinbo",
    companyType: "Logistics",
    status: "Active",
    totalShipments: 120,
    dateCreated: "2024-03-14",
  },
  {
    id: 2,
    companyName: "GreenX Transport",
    ownerName: "Mercy Adewale",
    companyType: "Transport",
    status: "Pending",
    totalShipments: 45,
    dateCreated: "2023-12-01",
  },
  {
    id: 3,
    companyName: "FleetBridge",
    ownerName: "John Okoro",
    companyType: "Delivery",
    status: "Pending",
    totalShipments: 89,
    dateCreated: "2024-01-22",
  },
  {
    id: 4,
    companyName: "SkyRiders",
    ownerName: "Fatima Bello",
    companyType: "Courier",
    status: "Active",
    totalShipments: 230,
    dateCreated: "2024-02-15",
  },
  {
    id: 5,
    companyName: "TrackWise Ltd",
    ownerName: "Emeka Uche",
    companyType: "Logistics",
    status: "Suspended",
    totalShipments: 160,
    dateCreated: "2023-11-09",
  },
  {
    id: 6,
    companyName: "Zenith Haulage",
    ownerName: "Chinelo Okafor",
    companyType: "Haulage",
    status: "Suspended",
    totalShipments: 34,
    dateCreated: "2023-10-17",
  },
  {
    id: 7,
    companyName: "RapidDrop",
    ownerName: "Ibrahim Salami",
    companyType: "Courier",
    status: "Active",
    totalShipments: 98,
    dateCreated: "2024-04-05",
  },
  {
    id: 8,
    companyName: "MoveIt Now",
    ownerName: "Linda Ojo",
    companyType: "Delivery",
    status: "Pending",
    totalShipments: 56,
    dateCreated: "2024-01-12",
  },
  {
    id: 9,
    companyName: "NextShip",
    ownerName: "Tunde Adebayo",
    companyType: "Shipping",
    status: "Active",
    totalShipments: 170,
    dateCreated: "2023-09-23",
  },
  {
    id: 10,
    companyName: "ExpressJet",
    ownerName: "Grace Oyetola",
    companyType: "Courier",
    status: "Pending",
    totalShipments: 22,
    dateCreated: "2024-05-08",
  },
  {
    id: 11,
    companyName: "CargoBase",
    ownerName: "Ahmed Musa",
    companyType: "Freight",
    status: "Active",
    totalShipments: 300,
    dateCreated: "2023-08-30",
  },
  {
    id: 12,
    companyName: "JetHaul",
    ownerName: "Victoria Ibe",
    companyType: "Haulage",
    status: "Suspended",
    totalShipments: 43,
    dateCreated: "2023-07-04",
  },
  {
    id: 13,
    companyName: "FastRoutes",
    ownerName: "Bola Obasanjo",
    companyType: "Logistics",
    status: "Active",
    totalShipments: 129,
    dateCreated: "2024-01-18",
  },
  {
    id: 14,
    companyName: "EazyTransport",
    ownerName: "Paul Ikenna",
    companyType: "Transport",
    status: "Suspended",
    totalShipments: 12,
    dateCreated: "2024-03-29",
  },
  {
    id: 15,
    companyName: "SmartCargo",
    ownerName: "Aisha Lawal",
    companyType: "Freight",
    status: "Active",
    totalShipments: 210,
    dateCreated: "2023-06-19",
  },
  {
    id: 16,
    companyName: "ShipSwift",
    ownerName: "Yusuf Garba",
    companyType: "Shipping",
    status: "Pending",
    totalShipments: 77,
    dateCreated: "2024-04-21",
  },
  {
    id: 17,
    companyName: "GoLogistics",
    ownerName: "Adaeze Nnamdi",
    companyType: "Logistics",
    status: "Pending",
    totalShipments: 31,
    dateCreated: "2024-02-08",
  },
  {
    id: 18,
    companyName: "UrbanMove",
    ownerName: "Samson Eze",
    companyType: "Delivery",
    status: "Suspended",
    totalShipments: 44,
    dateCreated: "2023-10-11",
  },
  {
    id: 19,
    companyName: "RocketShip",
    ownerName: "Opeyemi Alade",
    companyType: "Courier",
    status: "Active",
    totalShipments: 99,
    dateCreated: "2024-01-30",
  },
  {
    id: 20,
    companyName: "LinkFreight",
    ownerName: "Chigozie Obi",
    companyType: "Freight",
    status: "Suspended",
    totalShipments: 61,
    dateCreated: "2023-12-24",
  },
];
